services:
  
  db:
    image: postgres:15.4-bullseye
    ports:
      - 5432:5432
    restart: always
    env_file:
      .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  api:
    build:
      context: ./app
      dockerfile: ./app/Dockerfile
    image: sotw-api:latest
    ports:
      - "9000:8000"
    restart: always
    env_file:
      .env
    volumes:
      - ./app:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    image: sotw-frontend:latest
    command: npm run serve-prod
    ports:
      - "80:8080"
    depends_on:
      - db

volumes:
  postgres_data: