services:
  # app:
  #   image: sotw:latest
  #   restart: always
  #   environment:
  #     CAT: clarice
  db:
    image: postgres:15.4-bullseye
    ports:
      - 5432:5432
    restart: always
    env_file:
      .env # database credentials stored here
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres:/var/lib/postgresql/data