"""add spotify user id to user

Revision ID: 1908574502bf
Revises: 852081f16b0c
Create Date: 2024-06-08 09:36:05.548448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1908574502bf'
down_revision: Union[str, None] = '852081f16b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('spotify_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'spotify_user_id')
    # ### end Alembic commands ###
