"""refactor response

Revision ID: 1bd01b75462c
Revises: fdb40b947a25
Create Date: 2024-05-26 12:44:07.083912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd01b75462c'
down_revision: Union[str, None] = 'fdb40b947a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response', 'picked_song_1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('response', 'picked_song_2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response', 'picked_song_2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('response', 'picked_song_1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
