"""adding spotify info to user

Revision ID: 852081f16b0c
Revises: 1bd01b75462c
Create Date: 2024-05-26 15:53:38.739570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852081f16b0c'
down_revision: Union[str, None] = '1bd01b75462c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sotw', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('spotify_linked', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('spotify_access_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('spotify_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'spotify_refresh_token')
    op.drop_column('user', 'spotify_access_token')
    op.drop_column('user', 'spotify_linked')
    op.drop_column('sotw', 'owner_id')
    # ### end Alembic commands ###
