"""remove share id from sotw

Revision ID: 8b49ba04505e
Revises: b876ace39f58
Create Date: 2024-05-03 17:21:13.535813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b49ba04505e'
down_revision: Union[str, None] = 'b876ace39f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sotw', 'share_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sotw', sa.Column('share_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
