"""add timezone column to sotw

Revision ID: 98d0fe8cd496
Revises: dcd66e63ab0a
Create Date: 2025-04-14 18:41:05.690987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98d0fe8cd496"
down_revision: Union[str, None] = "dcd66e63ab0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "response",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "results",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.add_column("sotw", sa.Column("results_timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sotw", "results_timezone")
    op.alter_column(
        "results",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "response",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
