"""added user_playlist table

Revision ID: e993f07bf484
Revises: 46e6d9940b1c
Create Date: 2024-02-05 19:15:09.117935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e993f07bf484"
down_revision: Union[str, None] = "a3fcfd4650e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userplaylist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_link", sa.String(), nullable=True),
        sa.Column("sotw_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sotw_id"],
            ["sotw.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("user", "playlist_link")
    op.add_column(
        "usersongmatch", sa.Column("correct_guess", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersongmatch", "correct_guess")
    op.add_column(
        "user",
        sa.Column("playlist_link", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_table("userplaylist")
    # ### end Alembic commands ###
