"""upgrade sotw table

Revision ID: fb02c481b7c7
Revises: e993f07bf484
Create Date: 2024-03-13 20:44:17.699136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb02c481b7c7'
down_revision: Union[str, None] = 'e993f07bf484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('name', sa.String(), nullable=False))
    op.add_column('sotw', sa.Column('survey_datetime', sa.DateTime(), nullable=False))
    op.add_column('sotw', sa.Column('results_datetime', sa.DateTime(), nullable=False))
    op.add_column('sotw', sa.Column('share_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sotw', 'share_id')
    op.drop_column('sotw', 'results_datetime')
    op.drop_column('sotw', 'survey_datetime')
    op.drop_column('song', 'name')
    # ### end Alembic commands ###
