"""add survey to week

Revision ID: fdb40b947a25
Revises: 6a6c7116815c
Create Date: 2024-05-22 19:23:37.960667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb40b947a25'
down_revision: Union[str, None] = '6a6c7116815c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('picked_song_1_id', sa.Integer(), nullable=False))
    op.add_column('response', sa.Column('picked_song_2_id', sa.Integer(), nullable=False))
    op.drop_column('response', 'next_song_id')
    op.add_column('week', sa.Column('survey', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week', 'survey')
    op.add_column('response', sa.Column('next_song_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('response', 'picked_song_2_id')
    op.drop_column('response', 'picked_song_1_id')
    # ### end Alembic commands ###
